namespace Xcsb.Models;

public enum XEventType : byte
{
    KeyPress = 2,
    KeyRelease = 3,
    ButtonPress = 4,
    ButtonRelease = 5,
    MotionNotify = 6,
    EnterNotify = 7,
    LeaveNotify = 8,
    FocusIn = 9,
    FocusOut = 10,
    KeymapNotify = 11,
    Expose = 12,
    GraphicsExpose = 13,
    NoExpose = 14,
    VisibilityNotify = 15,
    CreateNotify = 16,
    DestroyNotify = 17,
    UnMapNotify = 18,
    MapNotify = 19,
    MapRequest = 20,
    ReParentNotify = 21,
    ConfigureNotify = 22,
    ConfigureRequest = 23,
    GravityNotify = 24,
    ResizeRequest = 25,
    CirculateNotify = 26,
    CirculateRequest = 27,
    PropertyNotify = 28,
    SelectionClear = 29,
    SelectionRequest = 30,
    SelectionNotify = 31,
    ColormapNotify = 32,
    ClientMessage = 33,
    MappingNotify = 34,
    LastEvent = 36,
    RequestError = 37,
    ValueError = 38,
    WindowError = 39,
    PixmapError = 40,
    AtomError = 41,
    CursorError = 42,
    FontError = 43,
    MatchError = 44,
    DrawableError = 45,
    AccessError = 46,
    AllocError = 47,
    ColormapError = 48,
    GContextError = 49,
    IDChoiceError = 50,
    NameError = 51,
    LengthError = 52,
    ImplementationError = 53,
    Unknown
}