using Microsoft.CodeAnalysis;
using System;
using System.Collections.Immutable;
using System.Diagnostics;
using System.Linq;

namespace Xcsb.Generators
{
    [Generator(LanguageNames.CSharp)]
    internal sealed class Class1 : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var compilationProvider = context.CompilationProvider
                .Select((a, _) =>
                    a.References
                    .Select(r => a.GetAssemblyOrModuleSymbol(r))
                    .OfType<IAssemblySymbol>()
                    .Select(a => a.Identity.Name)
                    .Where(a => a.StartsWith("Xcsb"))
                    .Distinct()
                    .OrderBy(n => n)
                    .ToImmutableArray());
            //Debugger.Launch();

            context.RegisterSourceOutput(compilationProvider, (ctx, packets) =>
            {
                ctx.AddSource("IXCProto.g.cs",
$$"""
// <auto-generated/>
namespace Xcsb
{

    public interface IXCProto
    {
        void Write();
    }

    public class XCpo : IXCProto
    {
        public void Write()
        {
            Console.WriteLine("{{String.Join(", ", packets)}}");
        }
    }
}

""");

                ctx.AddSource("XcsbClient.g.cs",
$$"""
namespace Xcsb
{

    public static class Charactor
    {
        public static IXCProto Dismember(this Xcsb.IXProto client)
        {
            return new XCpo();
        }
    }
}

""");
            });

//            context.RegisterPostInitializationOutput((ctx) =>
//            {
//                ctx.AddSource("IXCProto.g.cs",
//$$"""
//// <auto-generated/>
//namespace Xcsb
//{

//    public interface IXCProto
//    {
//        void Write();
//    }

//    public class XCpo : IXCProto
//    {
//        public void Write()
//        {
//            Console.WriteLine("Hellow");
//        }
//    }
//}

//""");

//                ctx.AddSource("XcsbClient.g.cs",
//$$"""
//namespace Xcsb
//{

//    public static class Charactor
//    {
//        public static IXCProto Dismember(this Xcsb.IXProto client)
//        {
//            return new XCpo();
//        }
//    }
//}

//""");
//            });

        }
    }
}