using Microsoft.CodeAnalysis;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Diagnostics;
using System.Linq;
using System.Text;

namespace Xcsb.Generators
{
    [Generator(LanguageNames.CSharp)]
    internal sealed class XcsbGenerator : IIncrementalGenerator
    {
        public static string TEXT = "Text";
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var extensationDefineAttributes = context.CompilationProvider
                .Select((a, _) => a.GetTypeByMetadataName("Xcsb.Generators.Attributes.XExtensationExporterAttribute"));
            var extensationAssemblys = context.CompilationProvider
                    .Select((a, _) =>
                        a.References
                            .Select(r => a.GetAssemblyOrModuleSymbol(r)).OfType<IAssemblySymbol>()
                            .Where(a => a.Identity.Name.StartsWith("Xcsb"))
                            .ToImmutableArray());
            var exportedInterfaces = extensationAssemblys
                .Combine(extensationDefineAttributes)
                .Select((pair, _) =>
                    pair.Left.SelectMany(a => GetAllTypes(a.GlobalNamespace))
                        .Where(t => pair.Right is not null
                            && t.TypeKind == TypeKind.Interface
                            && t.GetAttributes().Any(attr => SymbolEqualityComparer.Default.Equals(attr.AttributeClass, pair.Right)))
                        .Select(iface => (Interface: iface, Methods: GetAllInterfaceMethods(iface)))
                        .OrderByDescending(x => x.Methods.Length)
                        .ToImmutableArray());
            //Debugger.Launch();

            context.RegisterSourceOutput(exportedInterfaces, (ctx, packets) =>
            {

                var sb = new StringBuilder();
                for (var i = 0; i < packets.Length; i++)
                {
                    var packet = packets[i];
                    sb.Append("//");
                    sb.Append(packet.Interface.Name);
                    sb.AppendLine(" ->");
                    sb.Append("//");
                    sb.AppendLine("total methods:" + packet.Methods.Length);
                    if (i == 0) continue;
                    foreach (var method in packet.Methods)
                    {
                        sb.Append(method.ReturnType.ToDisplayString());
                        sb.Append(' ');
                        sb.Append(packet.Interface.ToDisplayString());
                        sb.Append('.');
                        sb.Append(method.Name);
                        sb.Append('(');

                        sb.Append(string.Join(
                            ", ",
                            method.Parameters.Select(a => $"{a.Type.ToDisplayString()} {a.Name}")));

                        sb.AppendLine(")");
                        sb.AppendLine("{");
                        sb.AppendLine("        return default;");
                        sb.AppendLine("}");
                    }
                }


                ctx.AddSource("IXCProto.g.cs",
$$"""
// <auto-generated/>
namespace Xcsb
{

    public class XProto{{TEXT}} : {{packets.Select(a => a.Interface.ToDisplayString()).FirstOrDefault()}}, IXProto{{TEXT}}
    {
        public XProto{{TEXT}}(Xcsb.IXConnection connection, ReadOnlySpan<char> failReason) : base(connection, failReason){}
        
        {{sb}}
    }


    public interface IXProto{{TEXT}} : {{string.Join(", ", packets.Select(a => a.Interface.ToDisplayString()))}}
    { }
}

""");

                ctx.AddSource("XcsbClient.g.cs",
$$"""
namespace Xcsb
{

    public static class XcsbExtensation
    {
        public static IXProto{{TEXT}} SetUpXcsb(this Xcsb.IXConnection client)
        {
            return new XProto{{TEXT}}();
        }
    }
}

""");
            });

            //            context.RegisterPostInitializationOutput((ctx) =>
            //            {
            //                ctx.AddSource("IXCProto.g.cs",
            //$$"""
            //// <auto-generated/>
            //namespace Xcsb
            //{

            //    public interface IXCProto
            //    {
            //        void Write();
            //    }

            //    public class XCpo : IXCProto
            //    {
            //        public void Write()
            //        {
            //            Console.WriteLine("Hellow");
            //        }
            //    }
            //}

            //""");

            //                ctx.AddSource("XcsbClient.g.cs",
            //$$"""
            //namespace Xcsb
            //{

            //    public static class Charactor
            //    {
            //        public static IXCProto Dismember(this Xcsb.IXProto client)
            //        {
            //            return new XCpo();
            //        }
            //    }
            //}

            //""");
            //            });

        }


        static IEnumerable<INamedTypeSymbol> GetAllTypes(INamespaceSymbol @namespace)
        {
            foreach (var member in @namespace.GetMembers())
            {
                if (member is INamespaceSymbol nestedNs)
                {
                    foreach (var type in GetAllTypes(nestedNs))
                        yield return type;
                }
                else if (member is INamedTypeSymbol type)
                {
                    yield return type;
                }
            }
        }
        static ImmutableArray<IMethodSymbol> GetAllInterfaceMethods(INamedTypeSymbol iface)
        {
            return iface
                .AllInterfaces
                .Append(iface)
                .SelectMany(i => i.GetMembers().OfType<IMethodSymbol>())
                .Where(m => m.MethodKind == MethodKind.Ordinary && !m.IsStatic)
                .ToImmutableArray();
        }

    }
}
