name: Build and Publish to nuget
on: workflow_dispatch
jobs:
  Build:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Checkout code
        uses: actions/checkout @v2
      - name: Setting Up dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Cleaning project
        run: dotnet clean ./Src/Xcsb.csproj
      - name: Building Project
        run: dotnet build ./Src/Xcsb.csproj -c Release
      - name: Debugging
        run: ls ./Src/bin/Release/ 
